apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: sonarqube
  namespace: sonarqube
spec:
  gateways:
  - istio-system/pixie-gateway
  hosts:
  - 'sonarqube.pixiescloud.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: sonarqube-sonarqube
        port:
          number: 9000